/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Login.java
 *
 * Created on Nov 3, 2011, 3:20:07 PM
 */

package nita.project.gui;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nita.project.db.LoginAuthentication;
import nita.project.db.MemberDB;
import nita.project.db.Session;
import nita.project.db.UserName;

/**
 *
 * @author Anil Bhaskar
 */

public class Login extends javax.swing.JFrame {


String n,p,name;
    /** Creates new form Login */
    public Login() {
        initComponents();
        msg.setVisible(false);
        setLocationRelativeTo(null);

    }
   

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        uname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        register = new javax.swing.JButton();
        loginbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        clerk = new javax.swing.JRadioButton();
        fac = new javax.swing.JRadioButton();
        admin = new javax.swing.JRadioButton();
        stu = new javax.swing.JRadioButton();
        loginbutton1 = new javax.swing.JButton();
        msg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14));
        jLabel1.setText("Login");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel2.setText("User Name");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel3.setText("Password");

        uname.setFont(new java.awt.Font("Tahoma", 0, 14));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14));
        jLabel4.setText("Login As");

        password.setFont(new java.awt.Font("Tahoma", 0, 14));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });

        register.setFont(new java.awt.Font("Tahoma", 0, 14));
        register.setText("New User");
        register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerActionPerformed(evt);
            }
        });

        loginbutton.setFont(new java.awt.Font("Tahoma", 0, 14));
        loginbutton.setText("login");
        loginbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbuttonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(102, 153, 255));

        clerk.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(clerk);
        clerk.setText("Clerk");

        fac.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(fac);
        fac.setText("Faculty");

        admin.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(admin);
        admin.setText("Administrator");

        stu.setBackground(new java.awt.Color(102, 153, 255));
        buttonGroup1.add(stu);
        stu.setText("Student");
        stu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(admin)
                .addGap(42, 42, 42)
                .addComponent(clerk)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(fac)
                .addGap(40, 40, 40)
                .addComponent(stu)
                .addGap(22, 22, 22))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(admin)
                    .addComponent(stu)
                    .addComponent(clerk)
                    .addComponent(fac))
                .addContainerGap())
        );

        loginbutton1.setFont(new java.awt.Font("Tahoma", 0, 14));
        loginbutton1.setText("Recover password");
        loginbutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbutton1ActionPerformed(evt);
            }
        });

        msg.setForeground(new java.awt.Color(255, 51, 0));
        msg.setText("Students are requested to login with their respective enrollment numbers.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(password, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uname, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(register, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(116, 116, 116)
                        .addComponent(loginbutton1, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(loginbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msg, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addComponent(msg, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(uname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)))
                    .addComponent(register, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loginbutton)
                    .addComponent(loginbutton1))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void loginbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbuttonActionPerformed


        if (!admin.isSelected() && !clerk.isSelected() && !fac.isSelected() && !stu.isSelected()) {
            JOptionPane.showMessageDialog(this, "please select the mode of login");
        } else {

            if (admin.isSelected()) {
                n = uname.getText();
                p = password.getText();
                if (n.isEmpty() || p.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "please enter the essential fields");

                } else {


                    boolean b = new LoginAuthentication().aut_ad(n, p);


                    if (b) {
                        Session ses = new Session();
                        ses.setSession(1);
                        UserName un = new UserName();
                        un.setUname(uname.getText());
                        JFrame s = new AdminHome(uname.getText());
                        this.setVisible(false);
                        s.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "username password do not match");

                    }
                }
            }

            if (clerk.isSelected()) {
                n = uname.getText();
                p = password.getText();
                boolean b = new LoginAuthentication().aut_clr(n, p);
                if (n.isEmpty() || p.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "please enter the essential fields");

                } else {
                    if (b) {
                        Session ses = new Session();
                        ses.setSession(2);
                        UserName un = new UserName();
                        un.setUname(uname.getText());
                        JFrame s = new ClerkHome(uname.getText());
                        this.setVisible(false);

                        s.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "username password do not match");

                    }
                }
            }

            if (fac.isSelected()) {
                n = uname.getText();
                p = password.getText();
                if (n.isEmpty() || p.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "please enter the essential fields");

                } else {
                    boolean b = new LoginAuthentication().auth_fac(n, p);
                    if (b) {
                        Session ses = new Session();
                        ses.setSession(3);
                        UserName un = new UserName();
                        un.setUname(uname.getText());
                        JFrame s = new FacultyHome(uname.getText());
                        this.setVisible(false);
                        s.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(this, "username password do not match");

                    }
                }
            }


            if (stu.isSelected()) {
                String u = (String) (uname.getText());
                String ps = password.getText();
                if (u.isEmpty() || ps.isEmpty()) {
                    JOptionPane.showMessageDialog(this, "please enter the essential fields");

                } else {
                    boolean b = new LoginAuthentication().aut_stu(u, ps);
                    if (b) {
                        Session ses = new Session();
                        ses.setSession(4);
                        UserName un = new UserName();
                        un.setUname(u);
                        JFrame s = new StudentHome(u);
                        this.setVisible(false);
                        s.setVisible(true);


                    } else {
                        JOptionPane.showMessageDialog(this, "username password do not match");

                    }
                }
            }
        }// TODO add your handling code here:


    }//GEN-LAST:event_loginbuttonActionPerformed

    private void registerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerActionPerformed
        // TODO add your handling code here:
        Register rg = new Register(this, rootPaneCheckingEnabled);
        rg.setVisible(true);

    }//GEN-LAST:event_registerActionPerformed

    private void loginbutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbutton1ActionPerformed
        if (!admin.isSelected() && !clerk.isSelected() && !fac.isSelected() && !stu.isSelected()) {
            JOptionPane.showMessageDialog(this, "please select the mode of user");

        } else {
            if (uname.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "please enter your user name");

            } else {
                if (admin.isSelected()) {

                    ArrayList<String> ar = new MemberDB().getAdmin();
                    if (!ar.contains(uname.getText())) {
                        JOptionPane.showMessageDialog(this, "admin with such name does not exist!");
                    } else {
                        RecoverPassAdmin n = new RecoverPassAdmin(this, rootPaneCheckingEnabled,uname.getText());
                        n.setVisible(true);
                    }


                }// TODO add your handling code here:
                else if (clerk.isSelected()) {
                    ArrayList<String> ar = new MemberDB().getclk();
                    if (!ar.contains(uname.getText())) {
                        JOptionPane.showMessageDialog(this, "clerk with such name does not exist!");
                    } else {


                        RecoverPassClerk m = new RecoverPassClerk(this, rootPaneCheckingEnabled,uname.getText());
                        m.setVisible(true);
                    }
                } else if (stu.isSelected()) {
                      String roll = (String)uname.getText();

                    ArrayList<String> ar = new MemberDB().getStuRoll();
                    if (!ar.contains(roll)) {
                        JOptionPane.showMessageDialog(this, "student with such roll number does not exist!");
                    } else {
                        RecoverPassStd o = new RecoverPassStd(this, rootPaneCheckingEnabled,roll);
                        o.setVisible(true);
                    }
                } else if (fac.isSelected()) {
                    ArrayList<String> ar = new MemberDB().getfac();
                    if (!ar.contains(uname.getText())) {
                        JOptionPane.showMessageDialog(this, "faculty with such name does not exist!");
                    } else {
                        RecoverPassFaculty p = new RecoverPassFaculty(this, rootPaneCheckingEnabled,uname.getText());
                        p.setVisible(true);

                    }
                }
            }
        }
    }//GEN-LAST:event_loginbutton1ActionPerformed

        private void stuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuActionPerformed
            // TODO add your handling code here:
             msg.setVisible(true);
        }//GEN-LAST:event_stuActionPerformed

    
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton admin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton clerk;
    private javax.swing.JRadioButton fac;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginbutton;
    private javax.swing.JButton loginbutton1;
    private javax.swing.JLabel msg;
    private javax.swing.JPasswordField password;
    private javax.swing.JButton register;
    private javax.swing.JRadioButton stu;
    private javax.swing.JTextField uname;
    // End of variables declaration//GEN-END:variables

}
