/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ManageMembership.java
 *
 * Created on Nov 16, 2011, 10:42:45 AM
 */

package nita.project.gui;

import java.lang.String;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nita.project.db.MemberDB;
import nita.project.db.Session;

/**
 *
 * @author Ritika Sahay
 */
public class ManageMembership extends javax.swing.JFrame {

    /** Creates new form ManageMembership */
    public ManageMembership() {
        initComponents();
        setLocationRelativeTo(null);
        Session ses =  new Session();
        int value = ses.getSession();
        if(value==2){
            clr_prof.setEnabled(false);
        }
        stro.setVisible(false);
        stu_roll.setVisible(false);
        fcn.setVisible(false);
        fac_name.setVisible(false);
        cln.setVisible(false);
        clr_name.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        panel = new javax.swing.JPanel();
        submit = new javax.swing.JButton();
        clr_prof = new javax.swing.JRadioButton();
        fac_prof = new javax.swing.JRadioButton();
        fcn = new javax.swing.JLabel();
        fac_name = new javax.swing.JTextField();
        stu_roll = new javax.swing.JTextField();
        stro = new javax.swing.JLabel();
        clr_name = new javax.swing.JTextField();
        cln = new javax.swing.JLabel();
        stu_prof = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Membership Management");

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        panel.setBackground(new java.awt.Color(153, 153, 255));

        submit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        submit.setText("view");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        clr_prof.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(clr_prof);
        clr_prof.setFont(new java.awt.Font("Tahoma", 0, 14));
        clr_prof.setText("View Clerk Profile");
        clr_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clr_profActionPerformed(evt);
            }
        });

        fac_prof.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(fac_prof);
        fac_prof.setFont(new java.awt.Font("Tahoma", 0, 14));
        fac_prof.setText("View Faculty Profile");
        fac_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fac_profActionPerformed(evt);
            }
        });

        fcn.setFont(new java.awt.Font("Tahoma", 0, 14));
        fcn.setText("Faculty Name");

        fac_name.setFont(new java.awt.Font("Tahoma", 0, 14));

        stu_roll.setFont(new java.awt.Font("Tahoma", 0, 14));

        stro.setFont(new java.awt.Font("Tahoma", 0, 14));
        stro.setText("Roll No");

        clr_name.setFont(new java.awt.Font("Tahoma", 0, 14));

        cln.setFont(new java.awt.Font("Tahoma", 0, 14));
        cln.setText("Clerk Name");

        stu_prof.setBackground(new java.awt.Color(153, 153, 255));
        buttonGroup1.add(stu_prof);
        stu_prof.setFont(new java.awt.Font("Tahoma", 0, 14));
        stu_prof.setText("View Student Profile");
        stu_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stu_profActionPerformed(evt);
            }
        });

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stro)
                            .addComponent(stu_roll, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(stu_prof)
                        .addGap(23, 23, 23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fac_prof)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fcn, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fac_name, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(clr_prof)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(clr_name, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cln))))
                .addGap(67, 67, 67))
            .addGroup(panelLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(submit, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(232, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stu_prof)
                            .addComponent(fac_prof))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stro)
                            .addComponent(fcn))
                        .addGap(18, 18, 18)
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(stu_roll, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fac_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(clr_prof)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cln, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(clr_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(submit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
if(!stu_prof.isSelected() && !fac_prof.isSelected() && !clr_prof.isSelected())
{
JOptionPane.showMessageDialog(this, "Please make a selection");
}
else if(stu_prof.isSelected())
{
  String i= stu_roll.getText();
         ArrayList<String> ar = new MemberDB().getStuRoll();
         if(!ar.contains(i))
         {
         JOptionPane.showMessageDialog(this, "student does not exist");
         }
         else{
             this.setVisible(false);
         JFrame f=new StudentProfile(stu_roll.getText());
         f.setVisible(true);
         }
}


else if(fac_prof.isSelected())
{
    String name=fac_name.getText();
   ArrayList<String> ar=new MemberDB().getfac();
   if(!ar.contains(name))
   {
   JOptionPane.showMessageDialog(this,"faculty odes not exist");
   }
   else{
       this.setVisible(false);
   JFrame f=new FacultyProfile();
   f.setVisible(true);
   }
}

else if(clr_prof.isSelected())
{
    String name=clr_name.getText();
    ArrayList<String> ar=new MemberDB().getclk();
   if(!ar.contains(name))
   {
   JOptionPane.showMessageDialog(this,"clerk odes not exist");
   }
   else{
   JFrame f=new ClerkProfile();
   f.setVisible(true);
   }

}// TODO add your handling code here:
    }//GEN-LAST:event_submitActionPerformed

    private void stu_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stu_profActionPerformed
stro.setVisible(true);
stu_roll.setVisible(true);
fcn.setVisible(false);
        fac_name.setVisible(false);
        cln.setVisible(false);
        clr_name.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_stu_profActionPerformed

    private void fac_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fac_profActionPerformed
 fcn.setVisible(true);
        fac_name.setVisible(true);
         stro.setVisible(false);
        stu_roll.setVisible(false);
                cln.setVisible(false);
        clr_name.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_fac_profActionPerformed

    private void clr_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clr_profActionPerformed
cln.setVisible(true);
        clr_name.setVisible(true);
         stro.setVisible(false);
        stu_roll.setVisible(false);
        fcn.setVisible(false);
        fac_name.setVisible(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_clr_profActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMembership().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel cln;
    private javax.swing.JTextField clr_name;
    private javax.swing.JRadioButton clr_prof;
    private javax.swing.JTextField fac_name;
    private javax.swing.JRadioButton fac_prof;
    private javax.swing.JLabel fcn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPanel panel;
    private javax.swing.JLabel stro;
    private javax.swing.JRadioButton stu_prof;
    private javax.swing.JTextField stu_roll;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables

}
