/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * UpdateClerk.java
 *
 * Created on Nov 24, 2011, 12:39:19 AM
 */

package nita.project.gui;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import nita.project.db.MemberDB;
import nita.project.objects.Clerk;

/**
 *
 * @author Ritika Sahay
 */
public class UpdateClerk extends javax.swing.JDialog {

    /** Creates new form UpdateClerk */
    public UpdateClerk(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
setLocationRelativeTo(null);
        ArrayList<Clerk> l=new MemberDB().WaitingClerk();

        DefaultTableModel model = (DefaultTableModel)table.getModel();
          model.setRowCount(l.size());
          Clerk ab = null;
        for (int i = 0; i < l.size(); i++){
            ab = l.get(i);
            model.setValueAt(ab.getClrName(), i, 0);
            model.setValueAt(ab.getClrjoin(), i, 1);

        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Clerk Requests");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Join Year"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton1.setText("Confirm Registration");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton6.setText("Reject Registration");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 51));
        jLabel1.setText("Clerk Requesting Registration");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jButton1)
                .addGap(135, 135, 135)
                .addComponent(jButton6)
                .addContainerGap(165, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton6))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int t=table.getSelectedRow();
        String k=(String) model.getValueAt(t, 0);
        boolean b=new MemberDB().ConfirmClerkRegistration(k);
        if(b) {
                        JOptionPane.showMessageDialog(this, "clerk registered!");
                        ArrayList<Clerk> l=new MemberDB().WaitingClerk();


          model.setRowCount(l.size());
          Clerk ab = null;
        for (int i = 0; i < l.size(); i++){
            ab = l.get(i);
            model.setValueAt(ab.getClrName(), i, 0);
            model.setValueAt(ab.getClrjoin(), i, 1);
        }
        }

        else{
            JOptionPane.showMessageDialog(this, "there seems to be some problem here!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        DefaultTableModel model = (DefaultTableModel)table.getModel();
        int t=table.getSelectedRow();
        String k=(String) model.getValueAt(t, 0);
        boolean b=new MemberDB().RemoveClerkRegistration(k);
        if(b) {
            ArrayList<Clerk> l=new MemberDB().WaitingClerk();

            model.setRowCount(l.size());
          Clerk ab = null;
        for (int i = 0; i < l.size(); i++){
            ab = l.get(i);
            model.setValueAt(ab.getClrName(), i, 0);
            model.setValueAt(ab.getClrjoin(), i, 1);
            JOptionPane.showMessageDialog(this, "registration removed from the list!");
        }
        }

        else{
            JOptionPane.showMessageDialog(this, "there seems to be some problem here!");
        }  // TODO add your handling code here:
}//GEN-LAST:event_jButton6ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UpdateClerk dialog = new UpdateClerk(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

}
